# agents:
#   queue: "AWS-queue"

# steps:
# # Step 1: Upload dynamic pipeline
# - label: "Upload Pipeline"
#   command: sleep 240 && echo "checking the aws autoscale"
#   key: Dependency_Step

# # Placeholder step to simulate dependencies
# - label: "Dependent Step check"
#   command: |
#     cat << EOF | buildkite-agent pipeline upload
#     steps:
#       - label: "Parallel Step"
#         command: echo "hi hi hi"
#         parallelism: 3  # 10 parallel jobs
#         agents:
#           queue: "AWS-queue"  # Specific queue for the parallel jobs
#         depends_on:
#           - "Dependency_Step"  # These jobs wait for the Dependency Step
#     EOF


# - label: "Dependent Step check"
#   command: |
#     cat << EOF | buildkite-agent pipeline upload
#     steps:
#       - label: "Parallel Step"
#         command: echo "hi hi hi"
#         parallelism: 3  # 10 parallel jobs
#         agents:
#           queue: "AWS-queue"  # Specific queue for the parallel jobs
#         depends_on:
#           - "Dependency_Step"  # These jobs wait for the Dependency Step
#     EOF

env:
  GHPAT_TOKEN: $(buildkite-agent secret get GHPAT_TOKEN)

steps:
- group: "Setup Group"
  key: "shopify"
  steps:
  - label: "Step 1: Install Dependencies"
    command: "echo 'Installing dependencies...'"

  - label: "Step 2: Run Setup Script"
    command: "echo 'Running setup script...'"

  - label: "Step 3: This needs to fail and pass on retry :danger:"
    command: |
      if [ "$BUILDKITE_RETRY_COUNT" == "1000" ]; then
        echo "Intentional failure"; exit 1
      else
        echo "Retrying and passing with GHPAT_TOKEN..."
      fi

- label: 'Step 5: Update GitHub Status'
  command: |
    outcome=$(buildkite-agent step get "state" --step "shopify")
    if [ "$outcome" != "hard_failed" ]; then
      echo "Updating GitHub status for parent pipeline with commit hash: $PARENT_COMMIT_HASH"
      curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GHPAT_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/AthreyaRay/sigkill_test/statuses/$PARENT_COMMIT_HASH \
        -d '{"state": "failure", "target_url": "https://buildkite.com/AthreyaRay/sigkill_test", "description": "Group steps completed", "context": "ci/buildkite"}'
    else
      echo "Group steps failed, skipping GitHub status update."
    fi

# - block: "Manual approval before sleep step"
#   prompt: "Do you want to proceed with the sleep step?"

- label: 'Step 6: Sleep for Debugging'
  command: sleep 10



