agents:
  queue: "AWS-queue"

steps:
# Step 1: Upload dynamic pipeline
- label: "Upload Pipeline"
  command: sleep 120 && echo "checking the aws autoscale"
  key: Dependency Step

# Placeholder step to simulate dependencies
- label: "Dependent Step check"
  command: |
    cat << EOF | buildkite-agent pipeline upload
    steps:
      - label: "Parallel Step"
        command: "./parallel-task.sh"
        parallelism: 10  # 10 parallel jobs
        agents:
          queue: "AWS-queue"  # Specific queue for the parallel jobs
        depends_on:
          - "Dependency Step"  # These jobs wait for the Dependency Step
    EOF
